[package]
name = "pass_manager"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.1"
clipboard-win = "4.5.0"
colored = "2.0.0"
rand = "0.8.5"
rkyv = { version = "0.7.41", features = ["validation"] }
rpassword = "7.2.0"
sha2 = "0.10.6"
sha3 = "0.10.7"
