[package]
name = "pass_manager"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.4.7", features = ["derive"] }
clipboard = "0.5.0"
rand = "0.8.5"
rkyv = { version = "0.7.42", features = ["validation"] }
rpassword = "7.2.0"
sha2 = "0.10.8"
