[package]
name = "pass_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.1"
colored = "2.0.0"
hex = "0.4.3"
rpassword = "7.2.0"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.89"
sha2 = "0.10.6"
