[package]
name = "pm"
version = "0.1.3"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
clipboard = "0.5.0"
dirs = "5.0.1"
hashbrown = { version = "0.14.2", features = ["rkyv"] }
lexopt = "0.3.0"
rand = "0.8.5"
rkyv = { version = "0.7.42", features = ["validation"] }
rpassword = "7.2.0"
sha2 = "0.10.8"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
strip = true
opt-level = "s"